[package]
name = "jsonschema-valid"
version = "0.1.0"
authors = ["Michael Droettboom <mdroettboom@mozilla.org>"]
description = "A simple JSON schema validator."
repository = "https://github.com/mdboom/jsonschema-valid"
readme = "README.md"
keywords = ["json schema"]
license = "MPL 2.0"

[dependencies]
serde_json = "1.0"
lazy_static = "1.1"
itertools = "0.8"
regex = "1"
url = "1.7"
chrono = "0.4"
