[package]
name = "jsonschema-valid"
version = "0.1.0"
authors = ["Michael Droettboom <mdboom@gmail.com>"]

[dependencies]
serde_json = "1.0"
lazy_static = "1.1"
itertools = "0.7"
regex = "1"
url = "1.7"
chrono = "0.3"
